
const mongoose = require('mongoose');

const bookingSchema = new mongoose.Schema({
  userEmail: { type: String, required: true },
  place: { type: String, required: true },
  name: { type: String, required: true },
  city: { type: String },
  phone: { type: String, required: true },
  vehicle: { type: String }, // Vehicle model
  license: { type: String, required: true }, // License plate
  timeSlot: [{ type: String, required: true }], // [entryTime, exitTime]
  amount: { type: String, required: true },
  ticketId: { type: String }, // ID generated by frontend
  createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Booking', bookingSchema);
